### PR TITLE
Update enum_column for Rails 4.1

### PR DESCRIPTION
**Pull request by jmcnally**
- lib/enum/enum_adapter.rb
  type_cast_code is removed in Rails 4.1

### CODE REVIEW

**Comment by jmcnally** [comment]
Not sure if this gem is being maintained anymore especially since ROR4.1 has its own kind of enum support.  But switching from enum_column to the new enums would be quite a bit of work, so it is still useful to keep the library usable.

**Comment by HonoreDB** [comment]
This doesn't appear to be maintained; I'm maintaining a fork at https://github.com/mdsol/enum_column with a security patch, published to RubyGems as `enum_column_strict`. You're welcome to make this PR there.

**Comment by alto** [comment]
+1 for releasing a new version including this patch!

**Comment by AnnikaSirapandjiNewWork** [comment]
+1

**Comment by imsoulfly** [comment]
+1 Like to see a new version release with this patch included! Please

**Pull request merged**
