### PR TITLE
Rails 3.2 Compatibility

### PR DESCRIPTION
**Pull request by mrzor**
Adapter name changed a bit. Support for < 3.2 is unchanged.

### CODE REVIEW

**Comment by mrzor** [comment]
Cheers

**Comment by kreeger** [comment]
Ah, _thank you_! I was just about to open a ticket and do a pull request myself. Could this, per chance, be versioned up and posted to RubyGems?

**Comment by electronick** [comment]
[to kreeger] yep, sure. I'll publish new gem version soon with other fixes.

**Comment by kreeger** [comment]
@electronick Thanks… you rock!

**Pull request merged**
